AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for Webhooks API
Globals:
  Function:
    Timeout: 3
Resources:
  SAMTwitterWebhookActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://raf-sam-test/1e807638a0a5f2f6ee0eb019096450eb
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          BUCKETNAME:
            Ref: BucketForOutputFile
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          Resource:
            Fn::GetAtt:
            - BucketForOutputFile
            - Arn
      Events:
        APIGateway:
          Type: Api
          Properties:
            Path: /webhook/twitter/cloudlopes
            Method: post
  SAMTwitterCRCResponse:
    DependsOn: BucketForOutputFile
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://raf-sam-test/cf90dc4ac9c3614bb78632e31b392f71
      Handler: lambda_function.crc
      Runtime: python3.6
      Events:
        APIGateway:
          Type: Api
          Properties:
            Path: /webhook/twitter/cloudlopes
            Method: get
  BucketForOutputFile:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
